#!/bin/bash

ARG DOCKER_IMAGE

FROM ${DOCKER_IMAGE}

RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
	apt-get install -yq apt-utils nano

COPY scripts/run.sh .

RUN chmod +x run.sh

ARG WORK_DIR

WORKDIR ${WORK_DIR}

ARG VOLUME

COPY . .

CMD [ "/bin/sh", "/run.sh" ]